// <auto-generated />
namespace KarateMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class userid11 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(userid11));
        
        string IMigrationMetadata.Id
        {
            get { return "201706281044201_userid11"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
